### ISSUE TITLE
HW 11-12

### ISSUE THREAD

**Issue by john45** [alex-rns/GH_RoR_shop#1]
Good Job!
there are some issues:
https://github.com/alex-rns/GH_RoR_shop/blob/1b1ac4b86986379ca279ca1ad7e458e2c303bcdb/config/routes.rb#L25 - resources must be in plural such as `orders` instead `order`
https://github.com/alex-rns/GH_RoR_shop/blob/1b1ac4b86986379ca279ca1ad7e458e2c303bcdb/config/routes.rb#L8
and
https://github.com/alex-rns/GH_RoR_shop/blob/1b1ac4b86986379ca279ca1ad7e458e2c303bcdb/config/routes.rb#L9
are redundant, you can use line 25 in this file for routing + add complete action.
Try to add to each file as controller or model empty last string.

**Comment by alex-rns** [comment]
Thanks! Fixed!
